#! /usr/bin/bash
clear
echo
echo "***** Service Katalog **************************************"
echo "*                                                          *"
echo "*    Demo, Hamburg 2025                                    *"
echo "*                                                          *"
echo "*                        Cumulus(Linux)1                   *"
echo "*                        SWP1       SWP2                   *"
echo "*                         |          |                     *"
echo "*      --------------------          -------------------   *"
echo "*      |                   DC Fabric                   |   *"
echo "*    SWP2                 Layer 3 EVPN               SWP2  *"
echo "*    Cumulus(Linux)0                      Cumulus(Linux2)  *"      
echo "*    SWP1                                            SWP1  *"
echo "*      |                  Automation via               |   *"
echo "*    eth1                    Ansible                 eth1  *"
echo "*    Ubuntu0                                      Ubuntu1  *"
echo "*                                                          *"
echo "*    1 = A  Hausputz                                       *"
echo "*    2 = B  EVPN-L2  MVP OK                                *"
echo "*    3 = X  EVPN-L3  MVP OK                                *"
echo "*    4 = Y  J2       Interaktiv                            *"
echo "*                                                          *"
echo "********************** end *********************************"
echo
echo 
PS3='Auswahl: '
options=("A" "B" "X" "Y" "Ende")
select opt in "${options[@]}"
do
    case $opt in
        "A")
            echo "Auswahl A"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.cleanup/main.yaml
            break
            ;;
        "B")
            echo "Auswahl B"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.G/main.yaml
            break
            ;;
        "X")
            echo "Auswahl X"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.L/main.yaml
            break
            ;;
        "Y")
            echo "Auswahl Y"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.N/main.yaml
            break
            ;;
         "Ende")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
