---
- hosts: cumulus1
  become: yes
  vars_files:
    - /home/cumulus/HH/.N/host_vars/cumulus1.yaml

  tasks:
    - name: j2 demo
      template: src=/home/cumulus/HH/.N/test.j2 dest=/etc/nvue.d/startup.yaml
