---
- hosts: leafspine
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: eBGP
      copy:
        src: /home/cumulus/HH/.F/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for leaf
      shell: nv config apply startup -y

- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/.F{{ inventory_hostname }}.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan
      shell: netplan apply
